version: '2'
services:
    myjupiterserverapp-app:
        image: myjupiterserverapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myjupiterserverapp-mysql:3306/myjupiterserverapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=myjupiterserverapp-elasticsearch:9300
        ports:
            - 8080:8080
    myjupiterserverapp-mysql:
        extends:
            file: mysql.yml
            service: myjupiterserverapp-mysql
    myjupiterserverapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myjupiterserverapp-elasticsearch
